source "https://rubygems.org"

ruby "2.7.0"

gem "sinatra", "2.0.8.1"
gem "sinatra-contrib"
gem "erubis"
gem "bcrypt"
gem "rack", "2.2.3"
gem "rack-protection", ">= 1.5.5"

gem "minitest"
gem "rack-test"

gem "redcarpet"