source "https://rubygems.org"

ruby "2.7.0"

gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "bcrypt"
gem "rack", ">=1.6.12"
gem "rack-protection", ">= 1.5.5"

gem "minitest"
gem "rack-test"

gem "redcarpet"