welcome: "=> Welcome to the Loan Calculator! -- ¡Bienvenido a la Calculadora de préstamos! -- ローン計算機へようこそ"
select_language: "\n=> Please select your language: -- Por favor seleccione su idioma: -- 言語を選択してください:
\n\n1) English\n2) Español\n3) 日本人" 
invalid_language: "=> Invalid Entry -- Entrada Invalida -- 無効なエントリ"

english:
  name: "What is your name?"
  hello: "=> Hello "
  loan_amount: "Please enter the loan amount (USD):"
  invalid_dollar: "Invalid Entry. Must be a dollar amount greater than zero."
  invalid_number: "Invalid Entry. Must be a number greater than zero."
  invalid: "Invalid Entry."
  apr: "Please enter the Annual Percentage Rate (%):"
  loan_duration: "Please enter the loan duration in months:"
  confirmation: "You have entered the following:"
  confirm_amount: "Loan Amount: $"
  confirm_apr: "APR:"
  confirm_duration: "Loan Duration:" 
  months: "months" 
  correct: "Press Y if this is correct, or N to start over."
  monthly_payment: "=> Your monthly payment is: $"
  principal: "Principal: $"
  interest: "Total Interest Paid: $"
  total: "Total Cost of Loan: $"
  again: "Press Y if you would like to run another calculation. Press N to exit."
  goodbye: "Go Buckeyes!" 

spanish:
  name: "¿Cuál es su nombre?"
  hello: "=> Hola "
  loan_amount: "Ingrese el monto del préstamo (USD):"
  invalid_dollar: "Entrada Invalida. Debe ser una cantidad en dólares mayor que cero."
  invalid_number: "Entrada Invalida. Debe ser un número mayor que cero."
  invalid: "Entrada Invalida."
  apr: "Ingrese la tasa de porcentaje anual (%):"
  loan_duration: "Ingrese la duración del préstamo en meses:"
  confirmation: "Has ingresado lo siguiente:"
  confirm_amount: "Monto del préstamo: $"
  confirm_apr: "Tasa de Porcentaje Anual:"
  confirm_duration: "Duración del Préstamo:" 
  months: "meses" 
  correct: "Presione Y si esto es correcto, o N para comenzar de nuevo."
  monthly_payment: "=> Tu pago mensual es: $"
  principal: "La Primera Figura: $"
  interest: "Total de Intereses Pagados: $"
  total: "Costo Total del Préstamo: $"
  again: "Presione Y si desea ejecutar otro cálculo. Presione N para salir."
  goodbye: "¡Van los Buckeyes!"

japanese:
  name: "お名前は何ですか？"
  hello: "=> こんにちは "
  loan_amount: "ローン金額（USD）を入力してください："
  invalid_dollar: "無効なエントリ。ゼロより大きい金額でなければなりません。"
  invalid_number: "無効なエントリ. ゼロより大きい数値でなければなりません。"
  invalid: "無効なエントリ"
  apr: "年次パーセンテージ率（％）を入力してください："
  loan_duration: "ローン期間を月単位で入力してください："
  confirmation: "次を入力しました。"
  confirm_amount: "ローン額：$"
  confirm_apr: "年間パーセンテージ："
  confirm_duration: "ローン期間:" 
  months: "ヶ月" 
  correct: "これが正しい場合は Y を押します, または最初からやり直す場合は N"
  monthly_payment: "=> あなたの毎月の支払いは: $"
  principal: "メイン: $"
  interest: "支払利息合計: $"
  total: "ローンの総費用: $"
  again: "別の計算を実行する場合は Y を押します. N を押して終了します"
  goodbye: "バックアイズに行く!"

