english:
  name: "What is your name?"
  hello: "Hello "
  loan_amount: "Please enter the loan amount (USD):"
  invalid: "Invalid Entry."
  apr: "Please enter the Annual Percentage Rate (%):"
  loan_duration: "Please enter the loan duration in months:"
  confirmation: "You have entered the following:"
  confirm_amount: "Loan Amount: $"
  confirm_apr: "APR:"
  confirm_duration: "Loan Duration:" 
  months: "months" 
  correct: "\nPress Y if this is correct."
  monthly_payment: "=> Your monthly payment is: $"
  principal: "Princial: $"
  interest: "Total Interest Paid: $"
  total: "Total Cost of Loan: $"
  again: "Press Y if you would like to run another calculation."
  goodbye: "Go Buckeyes!" 

spanish:
  name: "¿Cuál es su nombre?"
  hello: "Hola "
  loan_amount: "Ingrese el monto del préstamo (USD):"
  invalid: "Entrada Invalida."
  apr: "Ingrese la tasa de porcentaje anual (%):"
  loan_duration: "Ingrese la duración del préstamo en meses:"
  confirmation: "Has ingresado lo siguiente:"
  confirm_amount: "Monto del préstamo: $"
  confirm_apr: "Tasa de Porcentaje Anual:"
  confirm_duration: "Duración del Préstamo:" 
  months: "meses" 
  correct: "\nPresione Y si esto es correcto."
  monthly_payment: "=> Tu pago mensual es: $"
  principal: "La Primera Figura: $"
  interest: "Total de Intereses Pagados: $"
  total: "Costo Total del Préstamo: $"
  again: "Presione Y si desea ejecutar otro cálculo."
  goodbye: "¡Van los Buckeyes!"

japanese:
  name: "お名前は何ですか？"
  hello: "こんにちは "
  loan_amount: "ローン金額（USD）を入力してください："
  invalid: "無効なエントリ"
  apr: "年次パーセンテージ率（％）を入力してください："
  loan_duration: "ローン期間を月単位で入力してください："
  confirmation: "次を入力しました。"
  confirm_amount: "ローン額：$"
  confirm_apr: "年間パーセンテージ："
  confirm_duration: "ローン期間:" 
  months: "ヶ月" 
  correct: "\nこれが正しい場合は Y を押します."
  monthly_payment: "=> あなたの毎月の支払いは: $"
  principal: "メイン: $"
  interest: "支払利息合計: $"
  total: "ローンの総費用: $"
  again: "別の計算を実行する場合は Y を押します."
  goodbye: "バックアイズに行く!"

